### ISSUE TITLE
Code Review for Rui Yang

### ISSUE THREAD

**Issue by hughjazzman** [AY2122S1-CS2113T-F14-2/tp#173]
# @tryyang2001

- [ ] (`data/item/food/FoodList.java`, `data/item/exercise/ExerciseList.java`) Consider [avoiding arrowhead code here](https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-deep-nesting). [The code may also be repeated](https://nus-cs2113-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#minimise-code-duplication) in the two classes.

![image](https://user-images.githubusercontent.com/53231968/139525876-1144cf99-7f98-42ec-9e59-5669f4d22354.png)

**Comment by tryyang2001** [comment]
Thanks for your feedbacks for our team! I will try to change this part :)
