### ISSUE TITLE
[PE-D] Phrasing not clear in adding past and future activity

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#186]
![1.png](https://raw.githubusercontent.com/ruyian/ped/main/files/dee1411d-e173-4cd1-aaf0-73b91f241d4f.png)

\\

\\

Today is 29 Oct, however, when I follow the UG and adds the future exercise, it is counted as a past exercise

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ruyian/ped#5

**Comment by weidak** [comment]
Not very clear that past week is inclusive of today in the ug
