### ISSUE TITLE
[PE-D] Not allowed to add two food with same name to the food bank

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#189]
If I add McSpicy Meal of two different calories level to the foodbank, 

![1.png](https://raw.githubusercontent.com/ruyian/ped/main/files/215d373b-3975-4ae4-9b78-eed77ff6968e.png)

occurs. 

However, if I have two McSpicy Meals of different calory level that both need to be placed in the bank, the functionality fails.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: ruyian/ped#7

**Comment by weidak** [comment]
It was already explained in the ug that we do not allow duplicate item names for itembank as the same items should have the same calories unless defined otherwise by the user
