### ISSUE TITLE
[PE-D] Confusing UG statement

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#191]
In the UG

![1.png](https://raw.githubusercontent.com/ruyian/ped/main/files/4869b289-b730-4a3b-b479-410de2d3f706.png),
the statement is confusing.
What does it mean by day of the week where it could be 14 and 9 recurring exercises is added as a result?

To add on, this error is not explained clearly in the error message as well.
![1.png](https://raw.githubusercontent.com/ruyian/ped/main/files/1e799a31-af0d-4242-bce0-36e307802c9f.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: ruyian/ped#8

**Comment by weidak** [comment]
We will make this clearer by implementing commas to separate out the days of the week
