### ISSUE TITLE
[PE-D] Potential bug 2: Fail to terminate the program

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#196]
In the beginning, users are required to create a user profile. However, what if the user wants to terminate the program due to some other issues? It can be inconvenient if users cannot quit during the execution. Perhaps it would be better if users are allowed to quit at any time. 

![bug2.jpg](https://raw.githubusercontent.com/KairuiHu/ped/main/files/003cf502-22a7-4591-9c1d-8b4cdfad974d.jpg)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KairuiHu/ped#2

**Comment by weidak** [comment]
Same issue as #205
