### ISSUE TITLE
[PE-D] Unable to bye to exit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#205]
![1.png](https://raw.githubusercontent.com/ruyian/ped/main/files/0161fc9f-2a96-4d74-8e7c-fad07268d50d.png)

If I restart the programme with a new directory, I cant bye the programme.

I have to manually exit (Ctrl+C) and restart the jar to run again.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ruyian/ped#12

**Comment by weidak** [comment]
Add prompt for "bye" to exit: 1 to exit, 2 to set "bye" as name and 3 to set another name
