### ISSUE TITLE
[PE-D] Potential bug 7: Repeatition occurs when inserting records in exercise list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#206]
As shown below, users can insert the same records (same task, same date, same time, same calories) repeatedly. This type of insertion should be avoided as it is meaningless. The duplication may also lead to confusion. Moreover, a reminder for you is that users can input the same exercise with different calories. 

Possible suggestions: It would be better if you specify the exact time if you allow repeated records with the same date to eliminate confusion. But you can also specify any restrictions in your documentations, as I might have misunderstood this implementation. 

![bug7.png](https://raw.githubusercontent.com/KairuiHu/ped/main/files/f0c50154-32ec-47f3-a5b9-80e6883243d5.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: KairuiHu/ped#7

**Comment by tlyi** [comment]
We did not choose to prevent duplication of exercises as users may want to do the same exercise more than once in the same day. However, we agree that we could have clarified this better in our UG. Thanks!
